models:
  - legend: "RTMPose-X candidate"
#    model_path: "checkpoints/rtmpose/rtmpose-m_simcc-body7_pt-body7-halpe26_700e-256x192-4d3e73dd_20230605.pth"
#    config_path: "../configs/body_2d_keypoint/rtmpose/body8/rtmpose-m_8xb512-700e_body8-halpe26-256x192.py"
    model_path: "E:/Projects/mmpose/experiments_/delicate-chimp-466/model.pth"
    config_path: "E:/Projects/mmpose/experiments_/delicate-chimp-466/rtmpose-x_8xb256-700e_body8-halpe26-384x288.py"
    dataset_folder: "minio://"
    ann_file: "E:/Projects/mmpose/project/annotations/labelstudio_preds/Hands + Body Pose Annotation (2026-05-04 16-54-24).json"
#    dataset_folder: "D:/Datasets/val2017/val2017"
#    ann_file: "E:/Projects/mmpose/project/standard_anns/halpe_val_v1.json"
#    dataset_folder: "C:/Users/Alexander/Desktop/out/BL"
#    ann_file: "E:/Projects/mmpose/project/annotations/detection/coco/BL.json"
    num_joints: 26

  - legend: "ViTPose-halpe-simple-base v.0.9.3.0 build 9.2"
    model_path: "E:/ViTrackerStaff/models/pose_estimation/mmpose/PyTorch/ViTPose-base-simple-halpe26_8xb64-100e_coco-256x192_20260331.pth"
    config_path: "E:/Projects/ViTracker/core/pose_estimation/MMPose/configs/ViTPose-base-simple-halpe26_8xb64-100e_coco-256x192.yaml"
    dataset_folder: "minio://"
    ann_file: "E:/Projects/mmpose/project/annotations/labelstudio_preds/Hands + Body Pose Annotation (2026-05-04 16-54-24).json"
#    dataset_folder: "D:/Datasets/val2017/val2017"
#    ann_file: "E:/Projects/mmpose/project/standard_anns/halpe_val_v1.json"
#    dataset_folder: "C:/Users/Alexander/Desktop/out/BL"
#    ann_file: "E:/Projects/mmpose/project/annotations/detection/coco/BL.json"
    num_joints: 26

  # For adding new model:
  # - legend: "RTMPose-X"
  #   model_path: "checkpoints/rtmpose-x/..."
  #   config_path: "..."
  #   dataset_folder: "..."
  #   ann_file: "..."
  #   num_joints: 26
