models:
  - legend: "RTMPose-halpe-X default(26)"
    model_path: "E:/Projects/mmpose/project/checkpoints/rtmpose/rtmpose-x_simcc-body7_pt-body7-halpe26_700e-384x288-7fb6e239_20230606.pth"
    config_path: "E:/Projects/mmpose/configs/body_2d_keypoint/rtmpose/body8/rtmpose-x_8xb256-700e_body8-halpe26-384x288.py"
#    dataset_folder: "D:/Datasets/val2017/val2017"
#    ann_file: "E:/Projects/mmpose/project/annotations/standard/halpe_val_v1.json"
    dataset_folder: "minio://"
    ann_file: "E:/Projects/mmpose/project/annotations/split/val.json"
    anns_schema: "halpe26"
    expected_joints: 26
    gt_converter: "halpe_halpe26"
    pred_converter: null

  - legend: "ViTPose-simple-halpe-base 256x192 FT(26) v.0.9.3.0 build 9.2"
    model_path: "E:/ViTrackerStaff/models/pose_estimation/mmpose/PyTorch/ViTPose-base-simple-halpe26_8xb64-100e_coco-256x192_20260331.pth"
    config_path: "E:/Projects/ViTracker/core/pose_estimation/MMPose/configs/ViTPose-base-simple-halpe26_8xb64-100e_coco-256x192.yaml"
#    dataset_folder: "minio://datasets/Coco2017/val2017"
#    ann_file: "E:/Projects/mmpose/project/annotations/standard/halpe_val_v1.json"
    dataset_folder: "minio://"
    ann_file: "E:/Projects/mmpose/project/annotations/split/val.json"
    anns_schema: "halpe26"
    expected_joints: 26
    gt_converter: "halpe_halpe26"
    pred_converter: null

  - legend: "RTMPose-halpe-X 384x288 FT(26) candidate"
    model_path: "E:/Projects/mmpose/experiments_/delicate-chimp-466/model.pth"
    config_path: "E:/Projects/mmpose/experiments_/delicate-chimp-466/rtmpose-x_8xb256-700e_body8-halpe26-384x288.py"
#    dataset_folder: "minio://datasets/Coco2017/val2017"
#    ann_file: "E:/Projects/mmpose/project/annotations/standard/halpe_val_v1.json"
    dataset_folder: "minio://"
    ann_file: "E:/Projects/mmpose/project/annotations/split/val.json"
    anns_schema: "halpe26"
    expected_joints: 26
    gt_converter: "halpe_halpe26"
    pred_converter: null

#  - legend: "Sapiens2-0.4b default(133) adapt(26)"
#    model_path: ""
#    config_path: "E:/Projects/mmpose/.venv/Lib/site-packages/sapiens/pose/configs/keypoints308/shutterstock_goliath_3po/sapiens2_0.4b_keypoints308_shutterstock_goliath_3po-1024x768.py"
##    dataset_folder: "minio://datasets/Coco2017/val2017"
##    ann_file: "E:/Projects/mmpose/project/annotations/standard/halpe_val_v1.json"
#    dataset_folder: "minio://"
#    ann_file: "E:/Projects/mmpose/project/annotations/split/val.json"
#    anns_schema: "halpe26"
#    expected_joints: 308
#    gt_converter: "halpe_halpe26"
#    pred_converter: "goliath308_halpe26"
#
#  - legend: "Sapiens2-0.8b default(133) adapt(26)"
#    model_path: ""
#    config_path: "E:/Projects/mmpose/.venv/Lib/site-packages/sapiens/pose/configs/keypoints308/shutterstock_goliath_3po/sapiens2_0.8b_keypoints308_shutterstock_goliath_3po-1024x768.py"
##    dataset_folder: "minio://datasets/Coco2017/val2017"
##    ann_file: "E:/Projects/mmpose/project/annotations/standard/halpe_val_v1.json"
#    dataset_folder: "minio://"
#    ann_file: "E:/Projects/mmpose/project/annotations/split/val.json"
#    anns_schema: "halpe26"
#    expected_joints: 308
#    gt_converter: "halpe_halpe26"
#    pred_converter: "goliath308_halpe26"
#
#  - legend: "Sapiens2-1b default(133) adapt(26)"
#    model_path: ""
#    config_path: "E:/Projects/mmpose/.venv/Lib/site-packages/sapiens/pose/configs/keypoints308/shutterstock_goliath_3po/sapiens2_1b_keypoints308_shutterstock_goliath_3po-1024x768.py"
##    dataset_folder: "minio://datasets/Coco2017/val2017"
##    ann_file: "E:/Projects/mmpose/project/annotations/standard/halpe_val_v1.json"
#    dataset_folder: "minio://"
#    ann_file: "E:/Projects/mmpose/project/annotations/split/val.json"
#    anns_schema: "halpe26"
#    expected_joints: 308
#    gt_converter: "halpe_halpe26"
#    pred_converter: "goliath308_halpe26"

visualization:
  # Show interactive plot window after evaluation in pyplot
  show_plot: true
  generate_html: True
  # Where to save outputs (null = do not save)
  save_dir: "./results"
  # Radar plot Y-axis ticks (values between 0 and 1)
  #radar_xticks: [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  radar_xticks: null

metrics:
  COCO:
    # annotation file will be taken from individual config
    iou_type: keypoints
    score_mode: keypoint
    keypoint_score_thr: 0.2
    nms_mode: none
    nms_thr: 0.9
    # converters such as "gt_converter" or "pred_converter" are taken from the individual configuration
    format_only: False
    use_area: True
    iou_thrs: [0.95, 0.955, 0.96, 0.965, 0.97, 0.975, 0.98, 0.985, 0.99, 0.995, 0.9975]
  PCK:
    thresholds: [0.01, 0.009, 0.008, 0.007, 0.006, 0.005]
    norm_item: bbox
    keypoint_groups:
      head: [0, 1, 2, 3, 4]
      feet: [20, 21, 22, 23, 24, 25]
