models:
  - legend: "RTW-X (wholebody ann)"
    model_path: "E:/Projects/mmpose/project/checkpoints/rtmpose/rtmw-x_simcc-cocktail14_pt-ucoco_270e-384x288-f840f204_20231122.pth"
    config_path: "E:/Projects/mmpose/configs/wholebody_2d_keypoint/rtmpose/cocktail14/rtmw-x_8xb320-270e_cocktail14-384x288.py"
    dataset_folder: "minio://datasets/Coco2017/val2017"
    ann_file: "E:/Projects/mmpose/project/annotations/standard/coco_wholebody_val_v1.0.json"
    ann_format: CocoWholeBody
    meta_file: E:/Projects/mmpose/configs/_base_/datasets/coco_wholebody.py

  - legend: "RTW-X (halpe136)"
    model_path: "C:/Users/Alexander/Desktop/epoch_140.pth"
    config_path: "C:/Users/Alexander/Desktop/rtmw-x_8xb320-270e_cocktail14-384x288.py"
    dataset_folder: "minio://datasets/Coco2017/val2017"
    ann_file: "E:/Projects/mmpose/project/annotations/standard/coco_wholebody_val_v1.0.json"
    ann_format: CocoWholeBody
    meta_file: E:/Projects/mmpose/configs/_base_/datasets/coco_wholebody.py
    gt_converter: null
    pred_converters:
      - ann_field: bbox
        num_keypoints: 133
        mapping: halpe136_coco133

  - legend: "RTMpose-hand (hand ann)"
    model_path: "E:/Projects/mmpose/project/checkpoints/rtmpose/rtmpose-m_simcc-coco-wholebody-hand_pt-aic-coco_210e-256x256-99477206_20230228.pth"
    config_path: "E:/Projects/mmpose/configs/hand_2d_keypoint/rtmpose/coco_wholebody_hand/rtmpose-m_8xb32-210e_coco-wholebody-hand-256x256.py"
    dataset_folder: "minio://datasets/Coco2017/val2017"
    ann_file: "E:/Projects/mmpose/project/annotations/standard/coco_wholebody_val_v1.0.json"
    ann_format: CocoWholeBody
    meta_file: E:/Projects/mmpose/configs/_base_/datasets/coco_wholebody.py
    gt_converter: null
    pred_converters:
      - ann_field: lefthand_box
        num_keypoints: 133
        mapping: hand21_coco133_left
      - ann_field: righthand_box
        num_keypoints: 133
        mapping: hand21_coco133_right

  - legend: "RTMPose-halpe-X (halpe26 ann)"
    model_path: "E:/Projects/mmpose/project/checkpoints/rtmpose/rtmpose-x_simcc-body7_pt-body7-halpe26_700e-384x288-7fb6e239_20230606.pth"
    config_path: "E:/Projects/mmpose/configs/body_2d_keypoint/rtmpose/body8/rtmpose-x_8xb256-700e_body8-halpe26-384x288.py"
    dataset_folder: "minio://datasets/Coco2017/val2017"
    ann_file: "E:/Projects/mmpose/project/annotations/standard/coco_wholebody_val_v1.0.json"
    ann_format: CocoWholeBody
    meta_file: E:/Projects/mmpose/configs/_base_/datasets/coco_wholebody.py
    gt_converter: null
    pred_converters:
      - ann_field: bbox
        num_keypoints: 133
        mapping: halpe26_coco133

  - legend: "ViTPose-simple-halpe-base FT (halpe 26 ann)"
    model_path: "E:/ViTrackerStaff/models/pose_estimation/mmpose/PyTorch/ViTPose-base-simple-halpe26_8xb64-100e_coco-256x192_20260331.pth"
    config_path: "E:/Projects/ViTracker/core/pose_estimation/MMPose/configs/ViTPose-base-simple-halpe26_8xb64-100e_coco-256x192.yaml"
    dataset_folder: "minio://datasets/Coco2017/val2017"
    ann_file: "E:/Projects/mmpose/project/annotations/standard/coco_wholebody_val_v1.0.json"
    ann_format: CocoWholeBody
    meta_file: E:/Projects/mmpose/configs/_base_/datasets/coco_wholebody.py
    gt_converter: null
    pred_converters:
      - ann_field: bbox
        num_keypoints: 133
        mapping: halpe26_coco133

visualization:
  # Show interactive plot window after evaluation in pyplot
  show_plot: true
  generate_html: True
  # Where to save outputs (null = do not save)
  save_dir: "./results"
  # Radar plot Y-axis ticks (values between 0 and 1)
  #radar_xticks: [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  radar_xticks: null

metrics:
  COCO:
    type: CocoWholeBodyMetric
    # annotation file will be taken from individual config
    iou_type: keypoints
#    score_mode: bbox_keypoint
    score_mode: keypoint
    keypoint_score_thr: 0.2
#    nms_mode: oks_nms
    nms_mode: none
    nms_thr: 0.9
    # converters such as "gt_converter" or "pred_converter" are taken from the individual configuration
    format_only: False
    use_area: True
#    iou_thrs: [0.95, 0.955, 0.96, 0.965, 0.97, 0.975, 0.98, 0.985, 0.99, 0.995, 0.9975]
    iou_thrs: [0.5, 0.75]
  PCK:
#    thresholds: [0.01, 0.009, 0.008, 0.007, 0.006, 0.005]
    thresholds: [0.5, 0.25, 0.1, 0.05]
    norm_item: bbox
    keypoint_groups:
      head: [0, 1, 2, 3, 4]
      feet: [20, 21, 22, 23, 24, 25]