# Union configuration for accuracy.py и comparison.py
#
# accuracy.py:
#   python accuracy.py -c eval-config.yaml -o ./results
#
# comparison.py:
#   python comparison.py -c eval-config.yaml

models:
  - legend: "Default (RTMPose-M)"
    model_path: "checkpoints/rtmpose/rtmpose-m_simcc-body7_pt-body7-halpe26_700e-256x192-4d3e73dd_20230605.pth"
    config_path: "../configs/body_2d_keypoint/rtmpose/body8/rtmpose-m_8xb512-700e_body8-halpe26-256x192.py"
    dataset_folder: "D:/NewPoseCustom/2025-10-20 12-50-24"
    ann_file: "E:/Projects/mmpose/project/annotations/Pose Annotation.json"
    num_joints: 26

  - legend: "Finetune (ViTPose-Base, epoch 210)"
    model_path: "D:/MMPoseExp/2026-01-17 14_16_13/epoch_210.pth"
    config_path: "D:/MMPoseExp/2026-01-17 14_16_13/td-hm_ViTPose-base-simple_8xb64-210e_coco-256x192.py"
    dataset_folder: "D:/NewPoseCustom/2025-10-20 12-50-24"
    ann_file: "E:/Projects/mmpose/project/annotations/Pose Annotation.json"
    num_joints: 26

  # For adding new model:
  # - legend: "RTMPose-X"
  #   model_path: "checkpoints/rtmpose-x/..."
  #   config_path: "..."
  #   dataset_folder: "..."
  #   ann_file: "..."
  #   num_joints: 26
