import datetime
import itertools
import json
import logging
import traceback
from collections import defaultdict
from pathlib import Path
from typing import Any
import sys
import click
import cv2
import numpy as np
from mmengine.config import Config
from mmpose.visualization.fast_visualizer import FastVisualizer
from pycocotools.coco import COCO
from tqdm import tqdm

from deploy2serve.deployment.projects.sapiens.utils.adapters import visualizer_adapter
from deploy2serve.deployment.projects.sapiens.utils.palettes import COCO_WHOLEBODY_KPTS_COLORS, COCO_WHOLEBODY_SKELETON_INFO
from palettes import COCO_HALPE26_KPTS_COLORS, COCO_HALPE26_SKELETON_INFO

sys.path.insert(0, Path(__file__).parents[2].as_posix())
from project.label_studio.pipelines._mmpose import MMPose
from project.label_studio.pipelines.sapiens import Sapiens

log = logging.getLogger(__name__)


_CATEGORY_26 = {
    "id": 1, "name": "person", "supercategory": "person",
    "num_keypoints": 26,
    "keypoints": [
        "nose", "left_eye", "right_eye", "left_ear", "right_ear",
        "left_shoulder", "right_shoulder", "left_elbow", "right_elbow",
        "left_wrist", "right_wrist", "left_hip", "right_hip",
        "left_knee", "right_knee", "left_ankle", "right_ankle",
        "head", "neck", "hip", "left_big_toe", "left_small_toe",
        "left_heel", "right_big_toe", "right_small_toe", "right_heel",
    ],
}

_CATEGORY_133 = {
    "id": 1, "name": "person", "supercategory": "person",
    "num_keypoints": 133,
    "keypoints": [f"kp_{i}" for i in range(133)], # placeholder — replace with real names
}

_CATEGORY_BY_JOINTS = {26: _CATEGORY_26, 133: _CATEGORY_133}


def _make_coco_struct(num_joints: int) -> dict[str, Any]:
    now = datetime.datetime.now()
    return {
        "info": {
            "year": now.year,
            "version": "1.0",
            "description": "COCO annotations generated by AI pose estimation",
            "date_created": now.isoformat(),
        },
        "licenses": [{"id": 1, "name": "Unknown", "url": ""}],
        "categories": [_CATEGORY_BY_JOINTS[num_joints]],
        "images": [],
        "annotations": [],
    }


ImageInfo = dict[int, dict] # image_id → COCO image record
Detections = dict[int, list[list[float]]] # image_id → list of [x1, y1, x2, y2] boxes


def load_detections(annotations_json: str) -> tuple[Detections, ImageInfo]:
    coco = COCO(annotations_json)
    cat_ids = coco.getCatIds(catNms=["person"])
    img_ids = coco.getImgIds(catIds=cat_ids)

    images_info: ImageInfo = {img["id"]: img for img in coco.loadImgs(img_ids)}

    detections: Detections = defaultdict(list)
    for ann in coco.loadAnns(coco.getAnnIds(imgIds=img_ids, catIds=cat_ids)):
        x1, y1, w, h = ann["bbox"]
        detections[ann["image_id"]].append([x1, y1, x1 + w, y1 + h])

    # keep only images that have at least one detection
    valid_ids = [iid for iid in img_ids if detections.get(iid)]
    images_info = {iid: images_info[iid] for iid in valid_ids}
    detections  = {iid: detections[iid]  for iid in valid_ids}

    log.info(f"Loaded {len(images_info)} images with detections")
    return detections, images_info


def joints_to_coco(joints: np.ndarray, scores: np.ndarray) -> list[float]:
    vis = np.select([scores > 0.3, scores > 0.1], [2, 1], default=0).astype(float)
    return np.column_stack([joints, vis]).flatten().tolist()


def _save_json(path: Path, data: dict) -> None:
    tmp = path.with_suffix(".tmp")
    tmp.parent.mkdir(parents=True, exist_ok=True)
    tmp.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(path)


def _draw_preview(
    image: np.ndarray,
    visualizer: FastVisualizer,
    all_joints: np.ndarray,
    all_scores: np.ndarray,
    bboxes: list[list[float]],
) -> None:
    for person_joints, person_scores, bbox in zip(all_joints, all_scores, bboxes):
        visualizer.draw_pose(
            image,
            Config({"keypoints": person_joints[None], "keypoint_scores": person_scores[None]}), # noqa
        )
        x1, y1, w, h = bbox
        cv2.rectangle(image, (int(x1), int(y1)), (int(x1 + w), int(y1 + h)),
                      (50, 180, 80), 2, cv2.LINE_AA)


@click.command()
@click.option("--checkpoints-path", type=str,
              default=r"../checkpoints/rtmpose/rtmpose-x_simcc-body7_pt-body7-halpe26_700e-384x288-7fb6e239_20230606.pth",
              help="Path to model checkpoint (.pth or .plan).")
@click.option("--config-path", type=str,
              default=r"../../configs/body_2d_keypoint/rtmpose/body8/rtmpose-x_8xb256-700e_body8-halpe26-384x288.py",
              help="Path to mmpose config (RTMPose only; ignored for Sapiens).")
@click.option("--images-folder", type=str, default="D:/NewPoseCustom/stable",
              help="Root folder containing the images.")
@click.option("--detection-annotations", type=str,
              default="../annotations/detection/coco",
              help="COCO JSON with person bounding-box detections.")
@click.option("--output-json", type=str,
              default="../annotations/pose/coco",
              help="Destination path for the output COCO pose JSON.")
@click.option("--joints", type=click.Choice(["26", "133"]), default="26", show_default=True,
              help="Number of keypoints: 26 = Halpe-26 (RTMPose), 133 = WholeBody (Sapiens).")
@click.option("--device", type=str, default="cuda:0", show_default=True,
              help="Inference device (RTMPose only).")
@click.option("--score-thr", type=float, default=0.3, show_default=True,
              help="Keypoint visibility threshold for num_keypoints count.")
@click.option("--preview", is_flag=True, default=False,
              help="Show annotated preview window while processing.")
@click.option("--vis-delay", type=int, default=30, show_default=True,
              help="cv2.waitKey delay in ms (only with --preview).")
@click.option("--save-every", type=int, default=500, show_default=True,
              help="Save JSON incrementally every N images.")
def annotate(
    checkpoints_path: str,
    config_path: str,
    images_folder: str,
    detection_annotations: str,
    output_json: str,
    joints: str,
    device: str,
    score_thr: float,
    preview: bool,
    vis_delay: int,
    save_every: int,
) -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    num_joints = int(joints)
    out_path = Path(output_json).joinpath(f"{Path(images_folder).stem}.json")
    detection_annotations = f"{detection_annotations}/{Path(images_folder).stem}.json"
    detections, images_info = load_detections(detection_annotations)

    if num_joints == 26:
        model = MMPose(config_path, checkpoints_path, device)
        meta_info = visualizer_adapter(COCO_HALPE26_SKELETON_INFO, COCO_HALPE26_KPTS_COLORS)
    elif num_joints == 133:
        model = Sapiens(checkpoints_path)
        meta_info = visualizer_adapter(COCO_WHOLEBODY_SKELETON_INFO, COCO_WHOLEBODY_KPTS_COLORS)
    else:
        raise click.UsageError(f"Unsupported joint count: {num_joints}")

    visualizer = FastVisualizer(meta_info, radius=3, line_width=1, kpt_thr=score_thr) if preview else None

    if preview:
        cv2.namedWindow("Visualization", cv2.WINDOW_GUI_EXPANDED)

    coco_out = _make_coco_struct(num_joints)
    ann_id_gen = itertools.count(1)
    images_root = Path(images_folder)

    # Pre-populate images list (all images from detection file)
    for img_info in images_info.values():
        now = datetime.datetime.now().isoformat()
        coco_out["images"].append({
            "id": img_info["id"],
            "file_name": img_info["file_name"],
            "width": img_info["width"],
            "height": img_info["height"],
            "license": 1,
            "date_captured": img_info.get("date_captured", now),
        })

    image_ids = list(images_info.keys())

    for processed, image_id in enumerate(tqdm(image_ids, desc="Annotating"), start=1):
        img_info = images_info[image_id]
        image_path = images_root.joinpath(img_info["file_name"])
        boxes_xyxy = detections[image_id] # [[x1,y1,x2,y2], ...]

        if not image_path.exists():
            log.warning(f"Image not found, skipping: {image_path}")
            continue

        image = cv2.imread(image_path.as_posix())
        if image is None:
            log.warning(f"Cannot read image, skipping: {image_path}")
            continue

        try:
            # model returns (N, K, 2) joints and (N, K) scores
            joints, scores = model(image, np.array(boxes_xyxy))
        except Exception:
            log.error(f"Model failed on {image_path}:\n{traceback.format_exc()}")
            continue

        bboxes_xywh = []
        for i, (person_joints, person_scores, box_xyxy) in enumerate(
            zip(joints, scores, boxes_xyxy)
        ):
            x1, y1, x2, y2 = map(float, box_xyxy)
            bw, bh = x2 - x1, y2 - y1
            bbox = [x1, y1, bw, bh]
            bboxes_xywh.append(bbox)

            coco_out["annotations"].append({
                "id": next(ann_id_gen),
                "image_id": image_id,
                "category_id": 1,
                "keypoints": joints_to_coco(person_joints, person_scores),
                "num_keypoints": int(np.sum(person_scores > score_thr)),
                "bbox": bbox,
                "area": bw * bh,
                "iscrowd": 0,
                "segmentation": [],
            })

        if preview and visualizer is not None:
            _draw_preview(image, visualizer, joints, scores, bboxes_xywh)
            cv2.imshow("Visualization", image)
            key = cv2.waitKey(vis_delay)
            if key == ord("q"):
                log.info("Preview quit by user")
                preview = False
                cv2.destroyAllWindows()

        # Incremental save
        if processed % save_every == 0:
            _save_json(out_path, coco_out)
            log.info(f"Incremental save at {processed}/{len(image_ids)} → {out_path}")

    if preview:
        cv2.destroyAllWindows()

    _save_json(out_path, coco_out)

    click.echo(f"Saved → {out_path}")
    click.echo(f"Images: {len(coco_out['images'])}")
    click.echo(f"Annotations: {len(coco_out['annotations'])}")


if __name__ == "__main__":
    annotate()
