services:
  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: http://${MINIO_GLOBAL_HOST}:9000
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

  # create bucket on start
  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKET: ${MINIO_DEFAULT_BUCKET}
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
        mc mb --ignore-existing local/mlflow-artifacts;
        mc mb --ignore-existing local/datasets;
        mc anonymous set download local/datasets;
        echo 'MinIO buckets ready';
      "

  # Label Studio
  labelstudio:
    image: heartexlabs/label-studio:latest
    container_name: labelstudio
    restart: unless-stopped
    ports:
      - "8081:8081"
    command: label-studio start --host 0.0.0.0 --port 8081 --no-browser
    depends_on:
      minio:
        condition: service_healthy
    environment:
      DJANGO_DB: sqlite
      DEBUG: "true"
      LOCAL_FILES_SERVING_ENABLED: "true"
      LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT: /data/local-files
      LABEL_STUDIO_USERNAME: ${LABEL_STUDIO_USERNAME}
      LABEL_STUDIO_PASSWORD: ${LABEL_STUDIO_PASSWORD}
      # Label Studio searching MinIO by container name
      MINIO_STORAGE_ENDPOINT_URL: http://minio:9000
      MINIO_STORAGE_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_STORAGE_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/labelstudio:/label-studio/data
      - D:/:/data/local-files:ro
